version: '3.8'

services:
  postgres:
    image: postgres:15.4
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shoppingList
    volumes:
      - shopping-list-postgres-data:/var/lib/postgresql/data

volumes:
  shopping-list-postgres-data:
